### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by qq253498229** [xiaoshangfei/tserver1423#1]
执行 `docker run --rm -it terraria-test-server:1.0.0` 的时候没问题，可以正常启动。
但是当我使用 `docker run -d --rm -p 7777:7777 -v /root/tools/terraria/temp/Worlds:/usr/local/tserver/Worlds terraria-test-server:1.0.0` 命令启动的时候就报错了，错误信息如下：

```
100.0% - Final clean up - 100.0%
100.0% - Finalizing world - 0.0%
Terraria Server v1.4.2.3

Listening on port 7777
Type 'help' for a list of commands.

: ================
10/30/2021 08:50:48: Unhandled Exception
Thread: 6 [Server Input Thread]
Culture:
Exception: System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.Main.startDedInputCallBack () [0x00017] in <9633f74e7ae94ca9854ea47e5424de98>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <d1664be62cd44600bbd25f7afa292479>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <d1664be62cd44600bbd25f7afa292479>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d1664be62cd44600bbd25f7afa292479>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <d1664be62cd44600bbd25f7afa292479>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <d1664be62cd44600bbd25f7afa292479>:0
================
﻿﻿[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.Main.startDedInputCallBack () [0x00017] in <9633f74e7ae94ca9854ea47e5424de98>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <d1664be62cd44600bbd25f7afa292479>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <d1664be62cd44600bbd25f7afa292479>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d1664be62cd44600bbd25f7afa292479>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <d1664be62cd44600bbd25f7afa292479>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <d1664be62cd44600bbd25f7afa292479>:0
```

请问您遇到过这个错误吗，咋解决呢？

**Comment by qq253498229** [comment]
目录结构是这样的
![image](https://user-images.githubusercontent.com/31200516/139526748-2351b6a1-5c18-4a6f-a7a3-1ca2524554d6.png)

**Comment by qq253498229** [comment]
serverconfig.txt使用的是您提供的配置文件，一点没改

**Comment by qq253498229** [comment]
这是系统版本
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by xiaoshangfei** [comment]
> 



> 执行 `docker run --rm -it terraria-test-server:1.0.0` 的时候没问题，可以正常启动。 但是当我使用 `docker run -d --rm -p 7777:7777 -v /root/tools/terraria/temp/Worlds:/usr/local/tserver/Worlds terraria-test-server:1.0.0` 命令启动的时候就报错了，错误信息如下：
> 
> ```
> 100.0% - Final clean up - 100.0%
> 100.0% - Finalizing world - 0.0%
> Terraria Server v1.4.2.3
> 
> Listening on port 7777
> Type 'help' for a list of commands.
> 
> : ================
> 10/30/2021 08:50:48: Unhandled Exception
> Thread: 6 [Server Input Thread]
> Culture:
> Exception: System.NullReferenceException: Object reference not set to an instance of an object
>   at Terraria.Main.startDedInputCallBack () [0x00017] in <9633f74e7ae94ca9854ea47e5424de98>:0
>   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <d1664be62cd44600bbd25f7afa292479>:0
> ================
> ﻿﻿[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
>   at Terraria.Main.startDedInputCallBack () [0x00017] in <9633f74e7ae94ca9854ea47e5424de98>:0
>   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <d1664be62cd44600bbd25f7afa292479>:0
> ```
> 
> 请问您遇到过这个错误吗，咋解决呢？

**Comment by cattee1213** [comment]
> 执行 `docker run --rm -it terraria-test-server:1.0.0` 的时候没问题，可以正常启动。 但是当我使用 `docker run -d --rm -p 7777:7777 -v /root/tools/terraria/temp/Worlds:/usr/local/tserver/Worlds terraria-test-server:1.0.0` 命令启动的时候就报错了，错误信息如下：
> 
> ```
> 100.0% - Final clean up - 100.0%
> 100.0% - Finalizing world - 0.0%
> Terraria Server v1.4.2.3
> 
> Listening on port 7777
> Type 'help' for a list of commands.
> 
> : ================
> 10/30/2021 08:50:48: Unhandled Exception
> Thread: 6 [Server Input Thread]
> Culture:
> Exception: System.NullReferenceException: Object reference not set to an instance of an object
>   at Terraria.Main.startDedInputCallBack () [0x00017] in <9633f74e7ae94ca9854ea47e5424de98>:0
>   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <d1664be62cd44600bbd25f7afa292479>:0
> ================
> ﻿﻿[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
>   at Terraria.Main.startDedInputCallBack () [0x00017] in <9633f74e7ae94ca9854ea47e5424de98>:0
>   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <d1664be62cd44600bbd25f7afa292479>:0
>   at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <d1664be62cd44600bbd25f7afa292479>:0
> ```
> 
> 请问您遇到过这个错误吗，咋解决呢？

这个泰拉瑞亚服务端运行的时候需要保持控制台的交互，所以docker run 必须加 -it 而不能用-d，否则就会出错。Ubuntu里可以用tmux实现，我自己就是Ubuntu+tmux

**Comment by cattee1213** [comment]
> serverconfig.txt使用的是您提供的配置文件，一点没改

我自己疏忽了，说明文件忘记加上这个 -it的重要说明，现在已经加了
